---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /
    docker: true

- search:
    provider: custom
    url: https://www.ecosia.org/search?q=
    target: _blank
    suggestionUrl: https://ac.ecosia.org/autocomplete?type=list&q= # Optional
    showSearchSuggestions: true # Optional

- datetime:
    # 1/23/22, 1:37 PM
    format:
        dateStyle: short
        timeStyle: short
        hour12: true